# Generated by Django 2.0.3 on 2020-06-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtoppings',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemtoppings',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='menuitem',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
        migrations.DeleteModel(
            name='ItemToppings',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
