# Generated by Django 3.0.7 on 2020-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200608_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='specialty_price',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='topping_price',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
