# Generated by Django 3.0.7 on 2020-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200608_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
