# Generated by Django 3.0.7 on 2020-06-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menuitem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menuitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.MenuItem'),
        ),
    ]
