# Generated by Django 3.0.7 on 2020-06-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200608_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.OrderItem')),
                ('topping', models.ManyToManyField(blank=True, related_name='topping', to='orders.MenuItem')),
            ],
        ),
    ]
