# Generated by Django 3.0.7 on 2020-06-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_itemtopping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtopping',
            name='topping',
        ),
        migrations.AddField(
            model_name='itemtopping',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping', to='orders.MenuItem'),
        ),
    ]
